[general]
import = [
    "~/.config/alacritty/themes/iris.toml",
]
live_config_reload = true
ipc_socket = true

[env]
WINIT_X11_SCALE_FACTOR = "1.0"


[window]
dimensions = { columns = 0, lines = 0 }
position = "None"	# { x = 100, y = 100 } 
padding = { x = 0, y = 0 }
dynamic_padding = false
decorations = "Full"
opacity = 0.9
blur = false
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true
class = { instance = "Alacritty", general = "Alacritty" }
decorations_theme_variant = "None"
resize_increments = false
option_as_alt = "OnlyLeft"
level = "Normal"

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "HackGen Console NF", style = "Regular" }
bold = { family = "HackGen Console NF", style = "Bold" }
italic = { family = "HackGen Console NF", style = "Italic" }
bold_italic = { family = "HackGen Console NF", style = "Bold Italic" }
size = 14
offset = { x = 0, y = 0 }
# glyph_offset = { x = 0, y = 0 }
builtin_box_drawing = true

# [colors.primary]
# foreground = "#d8d8d8"
# background = "#181818"
# dim_foreground = "#828482"
# bright_foreground = "None"
# cursor = { text = "CellBlllground", cursor = "CellForeground" }
# vi_mode_cursor = { text = "CellBackground", cursor = "CellForeground" }
# 
# [colors.search]
# 
# [colors.normal]
# 
# [colors.bright]
# 
# [colors.dim]
# 
# [bell]

[selection]
save_to_clipboard = false

# [cousor]
# style = "Beam"
# blinking = "On"
# vi_mode_style = { shape = "Block", blinking = "Off" }

[terminal]
# shell = { program = "/bin/zsh", args = ["-1"] }

# [mouse]
# bindings = [
#     { mouse = "Right", mods = "Control", action = "Paste" },
#  ]

